language: python

os:
  - linux
  #- osx

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python -m pytest milon tests --cov=vasp

install:
  - pip install setuptools
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install .

after_success:
  - coveralls
